### PR TITLE
Constituency Map Styling

### PR DESCRIPTION
**Pull request by vaeyias**
image

Major Changes:

- Move election year slider onto map
- Resize map to be narrower
- Change values on the color legend and update the map colors data file
- Minor styling changes

Tasks Left
- Figure out how to resize the map itself based on screen size (the map's container resizes based on the screen size, but the map itself does not; did not work by resizing the width/height of the layer; I tried doing this with the zoom feature from leaflet but 5 zoom and 5.5 zoom are drastically different and there is nothing in between).
- Style data displayed on the side of the map
- Style "Loading..." before map loads in..

### CODE REVIEW

**Comment by JusticeV452** [comment]
Why did you resize the map to be narrower? I thought Dwai wanted the map to take up more space on the screen with a smaller election year column.

**Comment by vaeyias** [comment]
> Why did you resize the map to be narrower? I thought Dwai wanted the map to take up more space on the screen with a smaller election year column.

In the slack, Dwai said to clip the map at India's borders so that it doesn't show China.

**Comment by JusticeV452** [comment]
I think the solution would be to make the container larger while finding a way to make the India portion of the map take up more of the container (as you mentioned in the "Tasks Left" section). As it is now, there's a lot of unused space on the page, and it may be harder to interact with the map on smaller screens. In the meantime, if we don't want to show the map portion for other regions, the TileLayer of the MapBase can be removed to show only the geojson layer on a blank background. Let's see what Dwai thinks tomorrow.

**Review by JusticeV452 — APPROVED** [review]
Everything looks great! We'll keep the page layout as is, as discussed in the meeting since the map fits about as well as it can in the container, and we might need to utilize the space on the side later. My concern about the whitespace/narrow map at smaller desktop screen sizes is probably best addressed by adjusting the breakpoints, which we will have to adjust for mobile.

**Pull request merged**
